version: "3.9"

services:
  node:
    image: node:16
    container_name: desafio_tecnico_xp
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      DATABASE_URL: postgresql://root:root@db_desafio_tecnico:5432/investimento
      PRIVATE_KEY: secret_key

  db:
    platform: linux/x86_64
    image: postgres:13
    hostname: db_desafio_tecnico
    container_name: desafio_tecnico_xp_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

networks:
  default:
