version: "3.9"

services:
  node:
    image: node:16
    container_name: desafio_tecnico_xp
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      DATABASE_URL: mysql://root:secret@localhost:3306/investimento
      PRIVATE_KEY: secret_key

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: desafio_tecnico_xp_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306

networks:
  default:
